# Workflow to deploy a static site to GitHub Pages
name: Deploy Static Site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - main  # Adjust this if your default branch is different

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x' # Adjust Node.js version if needed

      - name: Install dependencies
        run: npm install # If you are using yarn, replace with yarn install

      - name: Build the app
        run: npm run build # For React apps, ensure your package.json has a "build" script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./build  # The output directory, for React it's typically 'build'

